import { escapeHtml } from "@jcendal/digital-pet-webviews/shared/escape-html.ts"
import { IntlModule } from "../../shared/i18n.ts"
export const battleMarkup = /* html */ `
<dialog id="battle-dialog" class="web-dialog" aria-labelledby="battle-title">
  <header class="dialog-head"><div><p class="dialog-eyebrow" data-i18n="web:battleMarkup.digimonArena">${escapeHtml(IntlModule.translate("battleMarkup.digimonArena"))}</p><h2 id="battle-title" data-i18n="web:battleMarkup.playerBattle">${escapeHtml(IntlModule.translate("battleMarkup.playerBattle"))}</h2></div><form method="dialog"><button class="dialog-close" aria-label="${escapeHtml(IntlModule.translate("battleMarkup.closeBattle"))}" data-i18n-aria-label="web:battleMarkup.closeBattle">✕</button></form></header>
  <div class="dialog-body">
    <p class="section-description" data-i18n="web:battle.description">${escapeHtml(IntlModule.translate("battle.description"))}</p>
    <label for="battle-own-code" data-i18n="web:battleMarkup.yourBattleCode">${escapeHtml(IntlModule.translate("battleMarkup.yourBattleCode"))}</label><div class="pair-code-row"><output id="battle-own-code" data-i18n="web:battleMarkup.connecting">${escapeHtml(IntlModule.translate("battleMarkup.connecting"))}</output><button id="battle-copy" type="button" data-i18n="web:battleMarkup.copy">${escapeHtml(IntlModule.translate("battleMarkup.copy"))}</button></div>
    <p class="setting-caption" data-i18n="web:battleMarkup.thisCodeChangesWhenYouReopenTheApp">${escapeHtml(IntlModule.translate("battleMarkup.thisCodeChangesWhenYouReopenTheApp"))}</p>
    <label for="battle-target" data-i18n="web:battleMarkup.otherPlayerSCode">${escapeHtml(IntlModule.translate("battleMarkup.otherPlayerSCode"))}</label><div class="pair-code-row"><input id="battle-target" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" autocomplete="off" placeholder="000000"><button id="battle-request" type="button" disabled data-i18n="web:battleMarkup.challenge">${escapeHtml(IntlModule.translate("battleMarkup.challenge"))}</button></div>
    <p id="battle-status" class="connection-status" role="status" aria-live="polite" data-i18n="web:battleMarkup.connecting2">${escapeHtml(IntlModule.translate("battleMarkup.connecting2"))}</p>
    <section id="battle-incoming" hidden><h3 data-i18n="web:battleMarkup.battleRequest">${escapeHtml(IntlModule.translate("battleMarkup.battleRequest"))}</h3><p id="battle-incoming-text"></p><div class="dialog-actions"><button id="battle-accept" class="primary-action" type="button" data-i18n="web:battleMarkup.acceptBattle">${escapeHtml(IntlModule.translate("battleMarkup.acceptBattle"))}</button><button id="battle-decline" type="button" data-i18n="web:battleMarkup.decline">${escapeHtml(IntlModule.translate("battleMarkup.decline"))}</button></div></section>
    <section id="battle-arena" hidden aria-label="${escapeHtml(IntlModule.translate("controller.playerBattle"))}" data-i18n-aria-label="web:controller.playerBattle"><p id="battle-score"></p><pre id="battle-artwork" aria-hidden="true"></pre></section>
  </div>
</dialog>`
