import { IntlModule as languageIntl } from "@jcendal/digital-pet-intl"
import { escapeHtml } from "@jcendal/digital-pet-webviews/shared/escape-html.ts"
import { IntlModule } from "../../shared/i18n.ts"

const deviceIcon = /* html */ `<svg class="option-icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M2 2h8v2H2zm0 2h2v12H2zm6 0h2v12H8zm-6 12h8v2H2zm2-3h4v2H4zm10-7h8v2h-8zm0 2h2v12h-2zm6 0h2v12h-2zm-6 12h8v2h-8zm2-3h4v2h-4zM10 8h4v2h-4zm0 4h4v2h-4z"/></svg>`
const eggIcon = /* html */ `<svg class="option-icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M10 2h4v2h-4zM8 4h2v4H8zm6 0h2v4h-2zM6 8h2v4H6zm10 0h2v4h-2zM4 12h2v6H4zm14 0h2v6h-2zM6 18h2v2H6zm10 0h2v2h-2zM8 20h8v2H8zM8 10h4v4H8zm4 6h4v2h-4z"/></svg>`

export const optionsMarkup = /* html */ `
<dialog id="options-dialog" class="web-dialog" aria-labelledby="options-title">
  <header class="dialog-head"><div><p class="dialog-eyebrow" data-i18n="web:optionsMarkup.digitalMonster">${escapeHtml(IntlModule.translate("optionsMarkup.digitalMonster"))}</p><h2 id="options-title" data-i18n="web:navigationMarkup.options">${escapeHtml(IntlModule.translate("navigationMarkup.options"))}</h2></div><form method="dialog"><button class="dialog-close" aria-label="${escapeHtml(IntlModule.translate("optionsMarkup.closeOptions"))}" data-i18n-aria-label="web:optionsMarkup.closeOptions">✕</button></form></header>
  <div class="dialog-body">
    <section class="options-section language-section">
      <label class="section-heading" id="language-label" for="language-select" data-i18n="intl:language.label">${escapeHtml(languageIntl.translate("language.label"))}</label>
      <p class="section-description" data-i18n="intl:language.description">${escapeHtml(languageIntl.translate("language.description"))}</p>
      <select id="language-select" aria-labelledby="language-label">
        ${["en", "ko", "es", "gl"].map((locale) => `<option value="${locale}">${escapeHtml(languageIntl.translate(`language.${locale}`))}</option>`).join("")}
      </select>
    </section>
    <section id="install-section" hidden>
      <button id="install-app" class="wide-action" type="button" data-i18n="web:installation.action">${escapeHtml(IntlModule.translate("installation.action"))}</button>
    </section>
    <section class="save-section"><h3 data-i18n="web:optionsMarkup.yourSave">${escapeHtml(IntlModule.translate("optionsMarkup.yourSave"))}</h3>
      <div class="save-choices">
        <label class="save-choice"><input id="source-computer" type="radio" name="save-source" value="sqlite"><span class="save-card"><span class="save-card-head"><strong data-i18n="web:optionsMarkup.computerSave">${escapeHtml(IntlModule.translate("optionsMarkup.computerSave"))}</strong><small id="computer-availability" class="save-badge"></small></span><small class="save-description" data-i18n="web:optionsMarkup.yourCompanionFromCursorOrOpencodeOnThis">${escapeHtml(IntlModule.translate("optionsMarkup.yourCompanionFromCursorOrOpencodeOnThis"))}</small></span></label>
        <p id="computer-connection-hint" class="hint" aria-live="polite"></p><button id="computer-retry" class="utility" type="button" hidden data-i18n="web:optionsMarkup.tryConnectingAgain">${escapeHtml(IntlModule.translate("optionsMarkup.tryConnectingAgain"))}</button>
        <label class="save-choice"><input id="source-browser" type="radio" name="save-source" value="browser"><span class="save-card"><span class="save-card-head"><strong data-i18n="web:optionsMarkup.thisBrowser">${escapeHtml(IntlModule.translate("optionsMarkup.thisBrowser"))}</strong><small class="save-badge" data-i18n="web:optionsMarkup.onDevice">${escapeHtml(IntlModule.translate("optionsMarkup.onDevice"))}</small></span><small class="save-description" data-i18n="web:optionsMarkup.aSeparateCompanionThatGrowsOverTimeTake">${escapeHtml(IntlModule.translate("optionsMarkup.aSeparateCompanionThatGrowsOverTimeTake"))}</small></span></label>
      </div>
      <p class="save-note"><span class="note-mark" aria-hidden="true"></span><span data-i18n="web:options.saveNote">${escapeHtml(IntlModule.translate("options.saveNote"))}</span></p>
      <aside id="browser-options-hint" class="source-notice" hidden><strong data-i18n="web:optionsMarkup.computerCompanion">${escapeHtml(IntlModule.translate("optionsMarkup.computerCompanion"))}</strong><p data-i18n="web:optionsMarkup.manageGrowthAndNewEggsInCursorOr">${escapeHtml(IntlModule.translate("optionsMarkup.manageGrowthAndNewEggsInCursorOr"))}</p></aside>
    </section>
    <section class="world-section"><h3 data-i18n="web:optionsMarkup.yourWorld">${escapeHtml(IntlModule.translate("optionsMarkup.yourWorld"))}</h3><p class="section-description" data-i18n="web:optionsMarkup.exploreANewHomeWithYourCompanion">${escapeHtml(IntlModule.translate("optionsMarkup.exploreANewHomeWithYourCompanion"))}</p><button id="world-button" class="wide-action" type="button" aria-haspopup="dialog"><span><span data-i18n="web:options.exploreRegions">${escapeHtml(IntlModule.translate("options.exploreRegions"))}</span><span id="world-current" data-i18n="web:optionsMarkup.dragonEyeLake">${escapeHtml(IntlModule.translate("optionsMarkup.dragonEyeLake"))}</span></span><span aria-hidden="true">→</span></button><button id="landscape-motion" class="wide-action" type="button" aria-pressed="false"><span data-i18n="web:optionsMarkup.movingLandscape">${escapeHtml(IntlModule.translate("optionsMarkup.movingLandscape"))}</span><span id="landscape-motion-state" class="value-badge" data-i18n="web:controller.off">${escapeHtml(IntlModule.translate("controller.off"))}</span></button><p class="setting-caption" data-i18n="web:optionsMarkup.scrollsGentlyInTheDirectionYourCompanionWalks">${escapeHtml(IntlModule.translate("optionsMarkup.scrollsGentlyInTheDirectionYourCompanionWalks"))}</p></section>
    <fieldset id="browser-options"><legend class="sr-only" data-i18n="web:optionsMarkup.browserCompanionOptions">${escapeHtml(IntlModule.translate("optionsMarkup.browserCompanionOptions"))}</legend>
      <section class="growth-section"><div class="section-heading"><h3 data-i18n="web:optionsMarkup.experienceToEvolve">${escapeHtml(IntlModule.translate("optionsMarkup.experienceToEvolve"))}</h3><span id="experience-amount" class="value-badge">100%</span></div>
        <p class="section-description" data-i18n="web:optionsMarkup.setThePaceOfYourCompanionSJourney">${escapeHtml(IntlModule.translate("optionsMarkup.setThePaceOfYourCompanionSJourney"))}</p>
        <div id="experience-control" class="experience-control" data-level="high">
          <label class="sr-only" for="experience-level" data-i18n="web:optionsMarkup.experienceToEvolve2">${escapeHtml(IntlModule.translate("optionsMarkup.experienceToEvolve2"))}</label>
          <input id="experience-level" class="experience-slider" type="range" min="0" max="2" step="1" value="2" aria-valuetext="High">
          <div class="range-labels"><button type="button" data-experience-index="0" aria-pressed="false"><span data-i18n="web:options.low">${escapeHtml(IntlModule.translate("options.low"))}</span><span>10%</span></button><button type="button" data-experience-index="1" aria-pressed="false"><span data-i18n="web:options.normal">${escapeHtml(IntlModule.translate("options.normal"))}</span><span>50%</span></button><button type="button" data-experience-index="2" aria-pressed="true"><span data-i18n="web:options.high">${escapeHtml(IntlModule.translate("options.high"))}</span><span>100%</span></button></div>
        </div>
        <p id="experience-description" class="setting-caption"></p>
      </section>
      <section class="devices-section"><div class="action-heading">${deviceIcon}<div><h3 data-i18n="web:optionsMarkup.connectDevices">${escapeHtml(IntlModule.translate("optionsMarkup.connectDevices"))}</h3><p class="section-description" data-i18n="web:optionsMarkup.yourCompanionOnAnotherScreen">${escapeHtml(IntlModule.translate("optionsMarkup.yourCompanionOnAnotherScreen"))}</p></div></div>
        <div id="paired-device" class="paired-card" hidden><span class="card-label" data-i18n="web:optionsMarkup.pairedDevice">${escapeHtml(IntlModule.translate("optionsMarkup.pairedDevice"))}</span><p id="pair-linked"></p><button id="pair-sync" class="primary-action" type="button" disabled><span data-i18n="web:optionsMarkup.syncCompanion">${escapeHtml(IntlModule.translate("optionsMarkup.syncCompanion"))}</span><span aria-hidden="true">↓</span></button><p class="setting-caption" data-i18n="web:optionsMarkup.bringsTheOtherDeviceSSaveHereWith">${escapeHtml(IntlModule.translate("optionsMarkup.bringsTheOtherDeviceSSaveHereWith"))}</p></div>
        <button id="pair-button" class="wide-action" type="button"><span id="pair-button-label" data-i18n="web:controller.pairDevices">${escapeHtml(IntlModule.translate("controller.pairDevices"))}</span><span aria-hidden="true">→</span></button>
        <button id="pair-forget" class="text-action" type="button" hidden data-i18n="web:optionsMarkup.forgetPairedDevice">${escapeHtml(IntlModule.translate("optionsMarkup.forgetPairedDevice"))}</button>
        <p id="pair-summary" class="connection-status" role="status" aria-live="polite"></p>
      </section>
      <section class="backup-section"><h3 data-i18n="web:optionsMarkup.backUpYourSave">${escapeHtml(IntlModule.translate("optionsMarkup.backUpYourSave"))}</h3><p class="section-description" data-i18n="web:optionsMarkup.keepACopyOfYourCompanionOutsideThis">${escapeHtml(IntlModule.translate("optionsMarkup.keepACopyOfYourCompanionOutsideThis"))}</p>
        <button id="backup-download" class="wide-action" type="button" data-i18n="web:optionsMarkup.downloadBackup">${escapeHtml(IntlModule.translate("optionsMarkup.downloadBackup"))}</button>
        <button id="backup-import" class="wide-action" type="button" data-i18n="web:optionsMarkup.importBackup">${escapeHtml(IntlModule.translate("optionsMarkup.importBackup"))}</button>
        <input id="backup-file" class="sr-only" type="file" accept=".json,application/json" aria-label="${escapeHtml(IntlModule.translate("optionsMarkup.chooseADigitalPetBackup"))}" data-i18n-aria-label="web:optionsMarkup.chooseADigitalPetBackup">
        <div id="backup-confirm" class="confirm-box" hidden><strong data-i18n="web:optionsMarkup.replaceThisBrowserSave">${escapeHtml(IntlModule.translate("optionsMarkup.replaceThisBrowserSave"))}</strong><p id="backup-preview"></p><p data-i18n="web:optionsMarkup.yourCurrentSaveCanBeRestoredFromOptions">${escapeHtml(IntlModule.translate("optionsMarkup.yourCurrentSaveCanBeRestoredFromOptions"))}</p><div class="dialog-actions"><button id="backup-accept" class="primary-action" type="button" data-i18n="web:optionsMarkup.replaceSave">${escapeHtml(IntlModule.translate("optionsMarkup.replaceSave"))}</button><button id="backup-cancel" type="button" data-i18n="web:optionsMarkup.cancel">${escapeHtml(IntlModule.translate("optionsMarkup.cancel"))}</button></div></div>
        <button id="backup-restore" class="text-action" type="button" hidden data-i18n="web:optionsMarkup.restorePreviousSave">${escapeHtml(IntlModule.translate("optionsMarkup.restorePreviousSave"))}</button>
        <p class="setting-caption" data-i18n="web:optionsMarkup.updatesKeepYourBrowserSaveADownloadedBackup">${escapeHtml(IntlModule.translate("optionsMarkup.updatesKeepYourBrowserSaveADownloadedBackup"))}</p>
      </section>
      <section class="new-partner-section"><div class="action-heading">${eggIcon}<div><h3 data-i18n="web:optionsMarkup.aNewJourney">${escapeHtml(IntlModule.translate("optionsMarkup.aNewJourney"))}</h3><p class="section-description" data-i18n="web:optionsMarkup.startFreshKeepYourPastCompanions">${escapeHtml(IntlModule.translate("optionsMarkup.startFreshKeepYourPastCompanions"))}</p></div></div>
        <button id="new-partner" class="wide-action" type="button"><span data-i18n="web:optionsMarkup.startANewEgg">${escapeHtml(IntlModule.translate("optionsMarkup.startANewEgg"))}</span><span aria-hidden="true">+</span></button>
        <p class="setting-caption" data-i18n="web:optionsMarkup.yourCurrentCompanionMovesToHistory">${escapeHtml(IntlModule.translate("optionsMarkup.yourCurrentCompanionMovesToHistory"))}</p>
        <div id="new-partner-confirm" class="confirm-box" hidden><strong data-i18n="web:optionsMarkup.readyForANewEgg">${escapeHtml(IntlModule.translate("optionsMarkup.readyForANewEgg"))}</strong><p data-i18n="web:optionsMarkup.yourCurrentCompanionWillStayInHistory">${escapeHtml(IntlModule.translate("optionsMarkup.yourCurrentCompanionWillStayInHistory"))}</p><div class="dialog-actions"><button id="new-partner-accept" class="primary-action" type="button" data-i18n="web:optionsMarkup.startNew">${escapeHtml(IntlModule.translate("optionsMarkup.startNew"))}</button><button id="new-partner-cancel" type="button" data-i18n="web:optionsMarkup.keepCompanion">${escapeHtml(IntlModule.translate("optionsMarkup.keepCompanion"))}</button></div></div>
      </section>
    </fieldset>
  </div>
  <p id="options-status" class="dialog-feedback" role="status" aria-live="polite"></p>
</dialog>
<dialog id="pair-dialog" class="web-dialog" aria-labelledby="pair-title">
  <header class="dialog-head"><div><p class="dialog-eyebrow" data-i18n="web:optionsMarkup.connectDevices">${escapeHtml(IntlModule.translate("optionsMarkup.connectDevices"))}</p><h2 id="pair-title" data-i18n="web:controller.pairDevices">${escapeHtml(IntlModule.translate("controller.pairDevices"))}</h2></div><form method="dialog"><button class="dialog-close" aria-label="${escapeHtml(IntlModule.translate("optionsMarkup.closePairing"))}" data-i18n-aria-label="web:optionsMarkup.closePairing">✕</button></form></header>
  <div class="dialog-body">
    <p class="section-description" data-i18n="web:optionsMarkup.enterTheOtherDeviceSCodeToBring">${escapeHtml(IntlModule.translate("optionsMarkup.enterTheOtherDeviceSCodeToBring"))}</p>
    <label for="pair-own-code" data-i18n="web:optionsMarkup.thisDevice">${escapeHtml(IntlModule.translate("optionsMarkup.thisDevice"))}</label><div class="pair-code-row"><output id="pair-own-code" data-i18n="web:optionsMarkup.loading">${escapeHtml(IntlModule.translate("optionsMarkup.loading"))}</output><button id="pair-copy" type="button" data-i18n="web:battleMarkup.copy">${escapeHtml(IntlModule.translate("battleMarkup.copy"))}</button></div>
    <label for="pair-target" data-i18n="web:optionsMarkup.otherDeviceCode">${escapeHtml(IntlModule.translate("optionsMarkup.otherDeviceCode"))}</label><div class="pair-code-row"><input id="pair-target" autocomplete="off" autocapitalize="characters" spellcheck="false" placeholder="${escapeHtml(IntlModule.translate("optionsMarkup.xxxxXxxxXxxxXxxx"))}" data-i18n-placeholder="web:optionsMarkup.xxxxXxxxXxxxXxxx"><button id="pair-request" type="button" disabled data-i18n="web:optionsMarkup.request">${escapeHtml(IntlModule.translate("optionsMarkup.request"))}</button></div>
    <p id="pair-status" class="connection-status" role="status" aria-live="polite" data-i18n="web:battleMarkup.connecting2">${escapeHtml(IntlModule.translate("battleMarkup.connecting2"))}</p>
    <section id="pair-incoming" hidden><h3 data-i18n="web:optionsMarkup.pairingRequest">${escapeHtml(IntlModule.translate("optionsMarkup.pairingRequest"))}</h3><p><span id="pair-incoming-description"></span><strong id="pair-incoming-code" hidden></strong></p><div class="dialog-actions"><button id="pair-send" class="primary-action" type="button" data-i18n="web:optionsMarkup.sendSavePair">${escapeHtml(IntlModule.translate("optionsMarkup.sendSavePair"))}</button><button id="pair-decline" type="button" data-i18n="web:battleMarkup.decline">${escapeHtml(IntlModule.translate("battleMarkup.decline"))}</button></div></section>
    <section id="pair-preview" hidden><h3 data-i18n="web:optionsMarkup.receivedSave">${escapeHtml(IntlModule.translate("optionsMarkup.receivedSave"))}</h3><p id="pair-preview-text"></p><div class="dialog-actions"><button id="pair-import" class="primary-action" type="button" data-i18n="web:optionsMarkup.replaceSavePair">${escapeHtml(IntlModule.translate("optionsMarkup.replaceSavePair"))}</button><button id="pair-reject" type="button" data-i18n="web:optionsMarkup.keepMine">${escapeHtml(IntlModule.translate("optionsMarkup.keepMine"))}</button></div></section>
    <button id="pair-restore" class="wide-action" type="button" hidden data-i18n="web:optionsMarkup.restorePreviousSave">${escapeHtml(IntlModule.translate("optionsMarkup.restorePreviousSave"))}</button>
  </div>
</dialog>`
